### ISSUE TITLE
Question - is swa-event-data meant to support only numerical values?

### ISSUE THREAD

**Issue by imflamboyant** [rehanvdm/serverless-website-analytics-client#23]
Hi,

I am trying the library out with a personal project and I noticed that my data is not sent with click events. Observing the network tab in the browser shows me that the data field is sent as `null` even though I have a string value set for it. When I inspected the source code of the client library I saw the following in `client-script.ts` on lines 80-81
```
const trackData = eventTarget.getAttribute('swa-event-data') || undefined;
const trackDataNumber = trackData ? Number(trackData) : undefined;
```

Does this mean that "data" is always meant to be numerical?

**Comment by rehanvdm** [comment]
Yes, in most/all web analytic systems I have come across it is always numbers. This is to translate events into something measurable. We currently do some light aggregation when showing that event.

![image](https://github.com/user-attachments/assets/1ab6589f-0d0a-47f4-9651-b3f08152b764)

What type of event do you want to send? And how do you see "consuming"/using the data from it?

**Comment by imflamboyant** [comment]
I have some links / buttons that I want to track clicks on, and I want to include the actual URL that the <a> holds so that I know what is actually being clicked.

In the image provided above, I interpret the numbers framed in red just as occurrences of 'date_filter_changed' event. What I would expect in the "data" field is perhaps the date to which it was changed, or something like that.

What are your thoughts, does this make sense?

**Comment by rehanvdm** [comment]
SWA (this project) allows this, it adds another dimension called category. So you can set your category to "external-link" then make the event the actual page URL, see the readme for usage. You can then click on the category on the dashboard to filter and see all events of the external-link category. 

FYI. With other tools you would have to make it `external-link: {link-here}`. For example, pay attention to the event being sent here https://usefathom.com/docs/events/external-clicks and here  https://usefathom.com/docs/events/404-page-tracking. But for SWA use the category as mentioned above.

**Comment by imflamboyant** [comment]
Awesome, thank you!
